# Generated by Django 5.1.2 on 2024-12-22 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emp_management', '0008_remove_employee_date_of_joining_must_be_less_than_or_equal_to_current_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborativeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='emp_management.employee')),
            ],
        ),
    ]
